### PR TITLE
Updated main_vif.py

### PR DESCRIPTION
**Pull request by 27rg5**

### CODE REVIEW

**Review by lsaca05 — CHANGES_REQUESTED** [review]
I tested this locally and while all the pipe errors were gone, the process was killed at epoch 5 due to excessive memory usage (>132GB):
```
Epoch 5/10
152/152 [==============================] - ETA: 0s - loss: 481.0035 - lambda_normalization_loss: 74.7847 - lambda_vf_loss: 481.0035 - lambda_vol_loss: 13668.6641./bozo.sh: line 3: 39323 Killed
```

Also, this time the program did not deallocate the memory. Still sitting at ~95% of what memory was used.

**Comment by 27rg5** [comment]
That is interesting, since for me it is different.

Can you check if your tensorflow is recognizing and using your GPU or not?

**Comment by lsaca05** [comment]
> That is interesting, since for me it is different.
> 
> Can you check if your tensorflow is recognizing and using your GPU or not?

Yes: `[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]`. I verify GPU utilization while running by using `watch -n 1 nvidia-smi`, and see spikes in GPU utilization every few seconds.

**Comment by 27rg5** [comment]
Made some changes to main_vif.py, model_vif.py and utils_vif.py. Try running the updated code now.

**Comment by 27rg5** [comment]
The latest updated code was able to delay the memory issue to epoch 17 (instead of epoch 10) for me. I have some updates that I want to try, but I am unable to try them due to the unavailability of GPU. You might have to try them out for me directly...

**Comment by 27rg5** [comment]
Changed model.fit to model.fit_generator and pushed changes just now, as discussed. It will give some warnings, but just ignore for now. 
Also, change your tensorflow version to 2.0.0 (stable version)

**Comment by lsaca05** [comment]
Confirmed program death with your changes + TensorFlow 2.12

After some struggling I managed to downgrade to TensorFlow 2.0.0. Here are the logs for my latest attempt, which errored:
```
/bin/bash: /home/mrispec/miniconda3/envs/tf/lib/libtinfo.so.6: no version information available (required by /bin/bash)
2023-05-23 13:53:05.931267: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2023-05-23 13:53:05.933144: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-05-23 13:53:05.933215: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: NVIDIA GeForce RTX 4090 major: 8 minor: 9 memoryClockRate(GHz): 2.52
pciBusID: 0000:01:00.0
2023-05-23 13:53:05.933294: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2023-05-23 13:53:05.933893: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2023-05-23 13:53:05.934529: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2023-05-23 13:53:05.934671: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2023-05-23 13:53:05.935301: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2023-05-23 13:53:05.935804: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2023-05-23 13:53:05.937444: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2023-05-23 13:53:05.937502: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-05-23 13:53:05.937566: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-05-23 13:53:05.937596: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
Mode: training
Tensorflow 2.0.0
Keras 2.2.4-tf
Training
Train: 152
Val: 19
Test: 25
2023-05-23 13:53:06.168114: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2023-05-23 13:53:06.171436: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2995200000 Hz
2023-05-23 13:53:06.171944: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5ce5a20 executing computations on platform Host. Devices:
2023-05-23 13:53:06.171954: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2023-05-23 13:53:06.214618: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-05-23 13:53:06.214747: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5acddc0 executing computations on platform CUDA. Devices:
2023-05-23 13:53:06.214759: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): NVIDIA GeForce RTX 4090, Compute Capability 8.9
2023-05-23 13:53:06.214852: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-05-23 13:53:06.214901: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: NVIDIA GeForce RTX 4090 major: 8 minor: 9 memoryClockRate(GHz): 2.52
pciBusID: 0000:01:00.0
2023-05-23 13:53:06.214919: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2023-05-23 13:53:06.214925: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2023-05-23 13:53:06.214929: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2023-05-23 13:53:06.214933: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2023-05-23 13:53:06.214938: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2023-05-23 13:53:06.214942: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2023-05-23 13:53:06.214946: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2023-05-23 13:53:06.214961: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-05-23 13:53:06.214998: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-05-23 13:53:06.215027: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2023-05-23 13:53:06.215036: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2023-05-23 13:53:06.215126: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-05-23 13:53:06.215129: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2023-05-23 13:53:06.215132: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2023-05-23 13:53:06.215156: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-05-23 13:53:06.215195: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-05-23 13:53:06.215237: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 19645 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 4090, pci bus id: 0000:01:00.0, compute capability: 8.9)
Training
WARNING:tensorflow:Using a generator with `use_multiprocessing=True` and multiple workers may duplicate your data. Please consider using the `keras.utils.Sequence` class.
Epoch 1/10
2023-05-23 13:53:14.245851: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2023-05-23 13:55:10.125603: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2023-05-23 13:55:11.336088: E tensorflow/stream_executor/cuda/cuda_blas.cc:428] failed to run cuBLAS routine: CUBLAS_STATUS_EXECUTION_FAILED
Traceback (most recent call last):
  File "main_vif.py", line 259, in <module>
    training_model(args)
  File "main_vif.py", line 118, in training_model
    workers=4
  File "/home/mrispec/miniconda3/envs/tf_dg/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 1297, in fit_generator
    steps_name='steps_per_epoch')
  File "/home/mrispec/miniconda3/envs/tf_dg/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_generator.py", line 265, in model_iteration
    batch_outs = batch_function(*batch_data)
  File "/home/mrispec/miniconda3/envs/tf_dg/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 973, in train_on_batch
    class_weight=class_weight, reset_metrics=reset_metrics)
  File "/home/mrispec/miniconda3/envs/tf_dg/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 264, in train_on_batch
    output_loss_metrics=model._output_loss_metrics)
  File "/home/mrispec/miniconda3/envs/tf_dg/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_eager.py", line 311, in train_on_batch
    output_loss_metrics=output_loss_metrics))
  File "/home/mrispec/miniconda3/envs/tf_dg/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_eager.py", line 252, in _process_single_batch
    training=training))
  File "/home/mrispec/miniconda3/envs/tf_dg/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_eager.py", line 127, in _model_loss
    outs = model(inputs, **kwargs)
  File "/home/mrispec/miniconda3/envs/tf_dg/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 891, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/home/mrispec/miniconda3/envs/tf_dg/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 708, in call
    convert_kwargs_to_constants=base_layer_utils.call_context().saving)
  File "/home/mrispec/miniconda3/envs/tf_dg/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 860, in _run_internal_graph
    output_tensors = layer(computed_tensors, **kwargs)
  File "/home/mrispec/miniconda3/envs/tf_dg/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 891, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/home/mrispec/miniconda3/envs/tf_dg/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/convolutional.py", line 197, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/home/mrispec/miniconda3/envs/tf_dg/lib/python3.7/site-packages/tensorflow_core/python/ops/nn_ops.py", line 1134, in __call__
    return self.conv_op(inp, filter)
  File "/home/mrispec/miniconda3/envs/tf_dg/lib/python3.7/site-packages/tensorflow_core/python/ops/nn_ops.py", line 639, in __call__
    return self.call(inp, filter)
  File "/home/mrispec/miniconda3/envs/tf_dg/lib/python3.7/site-packages/tensorflow_core/python/ops/nn_ops.py", line 238, in __call__
    name=self.name)
  File "/home/mrispec/miniconda3/envs/tf_dg/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_nn_ops.py", line 1524, in conv3d
    data_format=data_format, dilations=dilations, name=name, ctx=_ctx)
  File "/home/mrispec/miniconda3/envs/tf_dg/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_nn_ops.py", line 1599, in conv3d_eager_fallback
    ctx=_ctx, name=name)
  File "/home/mrispec/miniconda3/envs/tf_dg/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InternalError: Blas SGEMM launch failed : m=2097152, n=1, k=32 [Op:Conv3D]
```

I assume it's related to VRAM, since `nvidia-smi` shows it spiking to ~18-20GB before erroring out. No idea why it's a problem now rather than before. Same error occurs with use_multiprocessing=False and when omitting `workers`.

I'm not sure if downgrading is the play. Maybe we should migrate to PyTorch?

**Comment by 27rg5** [comment]
I think I know how to solve this specific error. Let me try that.
Also, are you using NVDIA RTX 4090? If yes, then please try to use a different GPU for now if you can....4090 is very new and its drivers, compatibility, etc can also be the cause of the issue.

I think we should try till the end of this week with Tensorflow. If that doesn't work, we'll shift to PyTorch.

**Comment by lsaca05** [comment]
I believe I found the solution: using GeneratorEnqueuer.

```
    train_enqueuer = tf.keras.utils.GeneratorEnqueuer(train_gen, use_multiprocessing=True)
    val_enqueuer = tf.keras.utils.GeneratorEnqueuer(val_gen, use_multiprocessing=True)
    train_enqueuer.start(workers=4, max_queue_size=10)
    val_enqueuer.start(workers=4, max_queue_size=10)

    print('Training')
    history = model.fit(
        train_enqueuer.get(),
        steps_per_epoch=len(train_set)/batch_size,
        epochs=args.epochs,
        validation_data = val_enqueuer.get(),
        validation_steps=len(val_set)/batch_size,
        callbacks = callbackscallbac,
        use_multiprocessing=False,
        workers=1
    )
```
Survived 10 epochs and never used more than ~50GB. My machine specifically was stuck at 27 GB RAM and 18 GB swap during the epoch. Between epochs RAM would top out at ~32GB and swap would remain around 16-18 GB. I seem to be getting the max speedup (that I've seen previously) at 5 min/epoch. I'll see if this survives a normal training run.

Source: https://github.com/tensorflow/tensorflow/issues/37505#issuecomment-806472122

**Comment by 27rg5** [comment]
Okay cool. One of my changes in the code went on till epoch 17 without the memory error. Let me know if you are able to cross that.

**Comment by 27rg5** [comment]
Reaching epoch 23 just by upgrading tensorflow and keras to 2.12 stable version

**Comment by lsaca05** [comment]
Looks like mine completed training at 53 epochs, which somehow is the fewest I've seen so far.

**Comment by 27rg5** [comment]
Okay, that is great! I added the extra Python code that you sent, and even my RAM usage is stable now. But my epochs are taking more time than usual. Using tensorflow 2.12.0.

Do you want me to try setting up multi-gpu training? Not sure if it will work or not, since I am more familiar with Pytorch.

**Pull request closed without merging**
